### ISSUE TITLE
Ready to use file

### ISSUE THREAD

**Issue by dataarchivist** [erlange/wbm-dl#1]
I wish to test your software, but without visual studio and the wish to install it just for a test, it’s hard to say something about your work. :)

**Comment by erlange** [comment]
Hi, sorry for the late response due to my vacation.

You don't need Visual Studio to run the executable.  As stated on the [README file here ](https://github.com/erlange/wbm-dl#Stand-Alone-Exexutable)you can download the stand alone executable files [here](https://github.com/erlange/wbm-dl/releases/download/v0.5/wbm-dl.zip)

**Comment by dataarchivist** [comment]
Very awesome! You may want to do an GUI Version too? :)

**Comment by erlange** [comment]
> 
> 
> Very awesome! You may want to do an GUI Version too? :)

The GUI version is on my todo list but my hands are currently tied on some other offline projects :)

**Comment by dataarchivist** [comment]
Ok, anyway, thanks for your work, it helps me a lot! :)
