### ISSUE TITLE
Stopped working.

### ISSUE THREAD

**Issue by starvedhorror** [erlange/wbm-dl#5]
I don't think it's on my end, since it was working fine a couple of weeks ago. Now, when trying to download anything it gives

> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at com.erlange.wbmdl.Program.SaveLog(List`1 logs, FileType extension, String path)
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at com.erlange.wbmdl.Program.Main(String[] args)

I'm on Windows 10, using the v0.5 exe.

**Comment by mikep2012** [comment]
Same error. Was working just fine before.
Would be great if it gets fixed.
Thank you!

**Comment by erlange** [comment]
Been away due to work

Done. It should work now.


> 
> 
> I don't think it's on my end, since it was working fine a couple of weeks ago. Now, when trying to download anything it gives
> 
> > Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
> > at com.erlange.wbmdl.Program.SaveLog(List`1 logs, FileType extension, String path) at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
> > at com.erlange.wbmdl.Program.Main(String[] args)
> 
> I'm on Windows 10, using the v0.5 exe.



> 
> 
> Same error. Was working just fine before.
> Would be great if it gets fixed.
> Thank you!

**Comment by mikep2012** [comment]
thanks man!


    On Tuesday, April 6, 2021, 05:42:55 PM GMT+3, Eri Airlangga ***@***.***> wrote:  
 
 


Been away due to work

Done. It should work now.


I don't think it's on my end, since it was working fine a couple of weeks ago. Now, when trying to download anything it gives


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at com.erlange.wbmdl.Program.SaveLog(List1 logs, FileType extension, String path) at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult1 result, Action`1 action)
at com.erlange.wbmdl.Program.Main(String[] args)


I'm on Windows 10, using the v0.5 exe.



Same error. Was working just fine before.
Would be great if it gets fixed.
Thank you!

**Comment by starvedhorror** [comment]
Thank you very much, it's working again! You should probably add the link to the latest version to the readme.

https://github.com/erlange/wbm-dl/blob/master/README.flat.md#Stand-Alone-Exexutable

(And also fix the word executable, ha)
